---
- hosts: all

  vars:
      build_config:
      - { id: "01", exitStatus: 0}
      - { id: "02", exitStatus: 1}
      - { id: "03", exitStatus: 0}
      - { id: "04", exitStatus: 0}
      - { id: "05", exitStatus: 1}
      - { id: "06", exitStatus: 0}
      - { id: "07", exitStatus: 1}
      - { id: "08", exitStatus: 0}
      - { id: "09", exitStatus: 1}
      - { id: "10", exitStatus: 0}
      - { id: "11", exitStatus: 1}
      - { id: "12", exitStatus: 0}
      - { id: "13", exitStatus: 1}
      - { id: "14", exitStatus: 0}
      - { id: "15", exitStatus: 1}
      - { id: "16", exitStatus: 0}
      - { id: "17", exitStatus: 1}
      - { id: "18", exitStatus: 0}
      - { id: "19", exitStatus: 1}
      - { id: "20", exitStatus: 0}
      - { id: "21", exitStatus: 1}
      - { id: "22", exitStatus: 0}
      - { id: "23", exitStatus: 1}
      - { id: "24", exitStatus: 0}
      - { id: "25", exitStatus: 1}
      - { id: "26", exitStatus: 0}
      - { id: "27", exitStatus: 1}
      - { id: "28", exitStatus: 0}
      - { id: "29", exitStatus: 1}
      - { id: "30", exitStatus: 0}

  tasks:
    - name: Install Jenkins key
      apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
      sudo: yes

    - name: Update source.list
      lineinfile: dest=/etc/apt/sources.list line="deb http://pkg.jenkins-ci.org/debian binary/"
      sudo: yes

    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install Jenkins
      apt: pkg=jenkins state=latest
      sudo: yes
      notify:
      - Restart Jenkins
      - Wait for port to be available
      - Wait for Jenkins to start
      - Retrieve Jenkins CLI
      - Copy job configuration
      - Copy view configuration
      - Create job
      - Create view

    - name: Install apache
      apt: pkg=apache2
      sudo: yes
      notify:
      - Disable default VirtualHost
      - Copy VirtualHost configuration
      - Enable VirtualHost
      - Set ServerName
      - Link resources
      - Restart apache

  handlers:

    - name: Restart Jenkins
      service: name=jenkins state=restarted
      sudo: yes

    - name: Wait for port to be available
      wait_for: port=8080

    - name: Wait for Jenkins to start
      uri: url=http://localhost:8080 return_content=yes
      register: response
      always_run: yes
      until: response.status == 200
      retries: 12
      delay: 5

    - name: Retrieve Jenkins CLI
      get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/home/vagrant

    - name: Copy job configuration
      template: src=resources/build dest=/home/vagrant/build{{ item.id }}
      with_items: build_config

    - name: Copy view configuration
      copy: src=resources/view1 dest=/home/vagrant/view1

    - name: Create job
      shell: java -jar /home/vagrant/jenkins-cli.jar -s http://localhost:8080/ create-job build{{ item.id }} < /home/vagrant/build{{ item.id }}
      with_items: build_config

    - name: Create view
      shell: java -jar /home/vagrant/jenkins-cli.jar -s http://localhost:8080/ create-view sample < /home/vagrant/view1

    - name: Disable default VirtualHost
      shell: a2dissite 000-default
      sudo: yes

    - name: Copy VirtualHost configuration
      copy: src=resources/VirtualHost dest=/etc/apache2/sites-available/jenkins.conf owner=www-data group=www-data
      sudo: yes

    - name: Enable VirtualHost
      shell: a2ensite jenkins
      sudo: yes

    - name: Set ServerName
      lineinfile: dest=/etc/apache2/apache2.conf line="ServerName localhost"
      sudo: yes

    - name: Link resources
      file: src=/vagrant dest=/var/www/vagrant owner=www-data group=www-data state=link
      sudo: yes

    - name: Restart apache
      service: name=apache2 state=restarted
      sudo: yes
